spring.datasource.url=jdbc:mysql://localhost:3306/vehicleservicedb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=vehicleservicesecretkey1234567890abcdef

spring.main.allow-circular-references=true

server.port=8081